name: programmable_video_web
description: A new flutter plugin project.
version: 0.1.0
# TODO: remove this line when web branch is ready to be merged into master
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  twilio_programmable_video_platform_interface: 
    path: ../programmable_video_platform_interface
  js: ^0.6.3
  enum_to_string: ^2.0.1
  dartlin: ^0.5.0

dev_dependencies:
  pedantic: ^1.8.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ProgrammableVideoPlugin
        fileName: twilio_programmable_video_web.dart

