name: twilio_programmable_video_platform_interface
description: A common platform interface for the programmable_video plugin.
version: 1.1.1
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video_platform_interface
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  enum_to_string: ^2.0.1
  plugin_platform_interface: ^2.1.8
  collection: ^1.17.0
  dartlin: ^0.6.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
